#install.packages("BiocManager")
#BiocManager::install("Biostrings")

library(tidyr)
library(dplyr)
library(lubridate)
library(stringr)
library(progress)
library(stringr)
library(parallel)
library(progress)
library("Biostrings")

library(ISOweek)
library(zoo)

library(ggplot2)
library(RColorBrewer)
library(colorspace)
library(openintro)
library(ggpubr)
library(parallel)

library(gridExtra)
library(gtable)
library(grid)
library(hrbrthemes)
library(pbmcapply)
